// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/testproject_3_version.test.ts.

/** The version of the `@tssuite/testproject_3` package. */
export const testproject3Version = '0.1.9';
